@startuml search_test
title Sequence Diagram - Teacher Search Test

actor Teacher
boundary "SearchTestPage" as UI <<boundary>>
control TestController
control TestService
control TestRepository
entity "Test" as test
database DB

Teacher -> UI: search()
UI -> TestController: search()
TestController -> TestService: searchTests()
TestService -> TestRepository: search()
TestRepository -> DB: SELECT tests
DB --> TestRepository: results
TestRepository -> test: Khởi tạo đối tượng (Map)
test --> TestRepository: Đối tượng Test
TestRepository --> TestService: results
TestService --> TestController: results
TestController --> UI: return result

@enduml