@startuml view_questions_sequence
title Sequence Diagram - Teacher View Questions Flow

actor Teacher
boundary "QuestionListPage" as UI <<boundary>>
control QuestionController
control QuestionService
control QuestionRepository
entity "Question" as question
database DB

Teacher -> UI: Xem danh sách câu hỏi
UI -> QuestionController: Xem danh sách câu hỏi

QuestionController -> QuestionService: Lấy danh sách câu hỏi

QuestionService -> QuestionRepository: Query questions
QuestionRepository -> DB: SELECT questions
DB --> QuestionRepository: question data
QuestionRepository -> question: Khởi tạo đối tượng (Map)
question --> QuestionRepository: Đối tượng Question
QuestionRepository --> QuestionService: return list
QuestionService --> QuestionController: return list

QuestionController --> UI: danh sách câu hỏi

@enduml