@startuml search_class
title Sequence Diagram - Teacher Search Class

actor Teacher
boundary "SearchClassPage" as UI <<boundary>>
control ClassController
control ClassService
control ClassRepository
database DB

Teacher -> UI: search()
UI -> ClassController: search()
ClassController -> ClassService: searchClasses()
ClassService -> ClassRepository: search()
ClassRepository -> DB: SELECT classes
DB --> ClassRepository: results
ClassRepository --> ClassService: results
ClassService --> ClassController: results
ClassController --> UI: return result

@enduml